# Generated by Django 2.2.5 on 2019-09-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('order_contents', models.TextField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('user_name', models.CharField(max_length=200)),
            ],
        ),
    ]
