# Generated by Django 2.2.5 on 2019-09-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order_details', models.TextField()),
                ('user_name', models.CharField(max_length=200)),
            ],
        ),
    ]
