# Generated by Django 2.2.5 on 2019-09-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='o_status',
            field=models.BooleanField(default=False),
        ),
    ]
